# Client Build
FROM trion/ng-cli as ng
# User node has write access
WORKDIR /home/node
# Copy packages files
COPY client/package*.json ./
# Install dependencies
RUN npm ci
# Copy everything else in client
COPY client/ ./
# Build frontend in production mode
RUN ng build --prod
# Get nginx to host on production
FROM nginx:1.17-alpine
# Copy template
COPY client/nginx/default.conf.template /etc/nginx/conf.d/default.conf.template
# Copy nginx config
COPY client/nginx/nginx.conf /etc/nginx/nginx.conf
# Copy dist to nginx
COPY --from=ng /home/node/dist/client/ /usr/share/nginx/html
# Bind the port with heroku's port
CMD /bin/sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'