version: "2"
services:
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8080:8080"
#     depends_on:
#       - neo4j
#   neo4j:
#     image: neo4j
#     ports:
#       - "7867:7867"
