version: "3"
services:
  backend:
    build: ./
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - ALPACA_KEY_ID=${ALPACA_KEY_ID}
      - ALPACA_SECRET_ID=${ALPACA_SECRET_ID}
      - IEXCLOUD_PUBLISHABLE_TOKEN_SANDBOX=${IEXCLOUD_PUBLISHABLE_TOKEN_SANDBOX}
      - IEXCLOUD_SECRET_TOKEN_SANDBOX=${IEXCLOUD_SECRET_TOKEN_SANDBOX}
      - IEXCLOUD_PUBLISHABLE_TOKEN_PROD=${IEXCLOUD_PUBLISHABLE_TOKEN_PROD}
      - IEXCLOUD_SECRET_TOKEN_PROD=${IEXCLOUD_SECRET_TOKEN_PROD}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_PROFILE_PICTURES_BUCKET=${AWS_PROFILE_PICTURES_BUCKET}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    links:
      - neo4j
    depends_on:
      - neo4j
  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    volumes:
      - /home/neo4j/data:/data
      - /home/neo4j/logs:/logs
