package com.capstone.moneytree.controller

import com.capstone.moneytree.service.api.UserService
import org.junit.Test
import org.springframework.http.HttpStatus

import static com.capstone.moneytree.utils.MoneyTreeTestUtils.createUser

import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.ActiveProfiles

import com.capstone.moneytree.dao.UserDao
import com.capstone.moneytree.dao.FollowsDao
import com.capstone.moneytree.exception.BadRequestException
import com.capstone.moneytree.model.node.User

import spock.lang.Specification

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@ActiveProfiles("dev")
class UserControllerIT extends Specification {

    @Autowired
    UserController userController

    @Autowired
    private UserService userService


    @Autowired
    UserDao userDao

    @Autowired
    FollowsDao fallowsDao


    def "a user is correctly persisted then fetched"() {
        setup: "Persist an initial user"
        userDao.save(createUser("test@test9009.com", "raz123412", "pass", "razine1234", "bensari2341", null))

        when: "We fetch the user"
        def persistedUser = userDao.findUserByEmail("test@test9009.com")

        then: "The user has the correct field"
        persistedUser.getEmail() == "test@test9009.com"
        persistedUser.getId() != null

        cleanup:
        userDao.delete(persistedUser)
    }

    def "a user is correctly updated; request body is valid"() {
        setup: "Persist an initial user"
        def persistedUser = userDao.save(createUser("test@test9009.com", "raz123412", "pass", "razine1234", "bensari2341", null))

        and: " a new user from request body"
        String newEmail = "test@test2123.com"
        String username = "razine123"
        String password = "encrypted"
        String firstName = "razineFristName"
        String lastName = "BENSARI-razine"
        User newUser = createUser(newEmail, username, password, firstName, lastName, null)
        newUser.setId(persistedUser.getId())

        when: " we update the user"
        def updatedUser = userController.editUserProfile(persistedUser.getId(), newUser)

        then: " the user should have the updated fields"
        updatedUser.getBody().getEmail() == newEmail
        updatedUser.getBody().getFirstName() == firstName
        updatedUser.getBody().getLastName() == lastName
        updatedUser.getBody().getUsername() == username

        cleanup: "delete the created user"
        userDao.delete(persistedUser)
        userDao.delete(newUser)
    }

    def "the passed user has a different id than the path"() {
        setup: "Persist an initial user"
        def persistedUser = userDao.save(createUser("test@test9092345209.com", "raz23452", "pass2345", "razine2345234", "bensari2345", null))

        and: " a new user from request body"
        String newEmail = "test@test2.com"
        String username = "Test"
        String password = "encrypted"
        String firstName = "John"
        String lastName = "Doe"
        // by saving a new user, an ID will be autogenerated
        User newUser = userDao.save(createUser(newEmail, username, password, firstName, lastName, null))

        when: " we update the user"
        userController.editUserProfile(persistedUser.getId(), newUser)

        then: " the user should have the updated fields"
        thrown(BadRequestException)

        cleanup: "delete the created user"
        userDao.delete(persistedUser)
        userDao.delete(newUser)
    }

    @Test
    def "a search request is made to retrieve only the essential properties of a User"() {
        setup: "Persist an initial set of users"
        userDao.save(createUser("test@test909234sd202.com", "raz23452", "pass2345", "razine2345234", "bensari2345", null))
        userDao.save(createUser("test@test2156ds587482.com", "raz54612", "pass1235", "razine8453123", "bensari2315", null))
        List<User> persistedUsers = new ArrayList<User>()
        persistedUsers.push(userDao.findUserByEmail("test@test909234sd202.com"))
        persistedUsers.push(userDao.findUserByEmail("test@test2156ds587482.com"))

        when: "we obtain the search users"
        def searchUsers = userDao.getSearchUsers()

        then: "each persisted user should be return represented with only the essential fields for the search list"
        for (Map<String, String> user : searchUsers) {
            for (User persistedUser : persistedUsers) {
                if (user.get("id") == Long.toString(persistedUser.getId())) {
                    assert user.get("id") == Long.toString(persistedUser.getId())
                    assert user.get("firstName") == persistedUser.getFirstName()
                    assert user.get("lastName") == persistedUser.getLastName()
                    assert user.get("email") == persistedUser.getEmail()
                    assert user.get("username") == persistedUser.getUsername()
                    assert user.get("avatarURL") == persistedUser.getAvatarURL()
                    assert user.get("alpacaApiKey") == null
                    assert user.get("balance") == null
                    assert user.get("score") == null
                    assert user.get("rank") == null
                    assert user.get("password") == null
                }
            }
        }

        cleanup: "delete the created user"
        for (User persistedUser : persistedUsers)
            userDao.deleteAll()
    }

    def "a user can follow another user in the database"() {
        setup: 'Persist an initial user'

        String newEmail1 = 'test@test.com'
        String username1 = 'daveUsername'
        String password1 = 'encrypted'
        String firstName1 = 'DaveFirstname'
        String lastName1 = 'DaveLastName'
        User user1 = createUser(newEmail1, username1, password1, firstName1, lastName1, '459fr2w-')
        userDao.save(user1)

        and: 'persist the other user we want to follow'

        String newEmail2 = 'test@test2123.com'
        String username2 = 'razine123'
        String password2 = 'encrypted'
        String firstName2 = 'razineFristName'
        String lastName2 = 'BENSARI-razine'
        User user2 = createUser(newEmail2, username2, password2, firstName2, lastName2, '258459fr2w-')
        userDao.save(user2)

        when: 'following the user'
        def response = userController.followUser(user1.getId(), user2.getId())

        then: 'user 1 should follow user 2'
        assert response.statusCode == HttpStatus.OK
        assert response.body == user2.getId()

        cleanup: 'delete the created users'
        userDao.delete(user1)
        userDao.delete(user2)
    }

    def "a user can unfollow another user in the database"() {
        setup: 'Persist an initial user'

        String newEmail1 = 'test@test.com'
        String username1 = 'daveUsername'
        String password1 = 'encrypted'
        String firstName1 = 'DaveFirstname'
        String lastName1 = 'DaveLastName'
        User user1 = createUser(newEmail1, username1, password1, firstName1, lastName1, '459fr2w-')
        userDao.save(user1)

        and: 'persist the other user we want to follow & follow it'

        String newEmail2 = 'test@test2123.com'
        String username2 = 'razine123'
        String password2 = 'encrypted'
        String firstName2 = 'razineFristName'
        String lastName2 = 'BENSARI-razine'
        User user2 = createUser(newEmail2, username2, password2, firstName2, lastName2, '258459fr2w-')
        userDao.save(user2)
        userController.followUser(user1.getId(), user2.getId())

        when: 'user1 unfollowing user2'
        def response = userController.unfollowUser(user1.getId(), user2.getId())

        then: 'user 1 should unfollow user 2'
        assert response.statusCode == HttpStatus.OK
        assert response.body == user2.getId()

        cleanup: 'delete the created users'
        userDao.delete(user1)
        userDao.delete(user2)
    }

    def "a list of followings for user should be correctly returned"() {
        setup: 'Persist an initial user'

        String newEmail1 = 'test@test.com'
        String username1 = 'daveUsername'
        String password1 = 'encrypted'
        String firstName1 = 'DaveFirstname'
        String lastName1 = 'DaveLastName'
        User user1 = createUser(newEmail1, username1, password1, firstName1, lastName1, '459fr2w-')
        userDao.save(user1)

        and: 'persist the other user we want to follow & follow it'

        String newEmail2 = 'test@test2123.com'
        String username2 = 'razine123'
        String password2 = 'encrypted'
        String firstName2 = 'razineFristName'
        String lastName2 = 'BENSARI-razine'
        User user2 = createUser(newEmail2, username2, password2, firstName2, lastName2, '258459fr2w-')
        userDao.save(user2)
        userController.followUser(user1.getId(), user2.getId())

        when: 'getFollowings of user1'
        def response = userController.getFollowings(user1.getId())

        then: 'should have user2 in the response body'
        assert response[0].getFirstName() == user2.getFirstName()

        cleanup: 'delete the created users'
        userDao.delete(user1)
        userDao.delete(user2)
    }

    def "a list of followers for user should be correctly returned"() {
        setup: 'Persist an initial user'

        String newEmail1 = 'test@test.com'
        String username1 = 'daveUsername'
        String password1 = 'encrypted'
        String firstName1 = 'DaveFirstname'
        String lastName1 = 'DaveLastName'
        User user1 = createUser(newEmail1, username1, password1, firstName1, lastName1, '459fr2w-')
        userDao.save(user1)

        and: 'persist the other user we want to follow & follow it'

        String newEmail2 = 'test@test2123.com'
        String username2 = 'razine123'
        String password2 = 'encrypted'
        String firstName2 = 'razineFristName'
        String lastName2 = 'BENSARI-razine'
        User user2 = createUser(newEmail2, username2, password2, firstName2, lastName2, '258459fr2w-')
        userDao.save(user2)
        userController.followUser(user1.getId(), user2.getId())

        when: 'getFollowers of user2'
        def response = userController.getFollowers(user2.getId())

        then: 'should have user1 in the response body'
        assert response[0].getFirstName() == user1.getFirstName()

        cleanup: 'delete the created users'
        userDao.delete(user1)
        userDao.delete(user2)
    }
}
