#!/bin/bash

# Run at the root of the project the command:
# ln -s -f ../../hooks/pre-commit .git/hooks/pre-commit && chmod +x ./hooks/pre-commit
# To make the pre-commit linter available in your Git hooks

function get_latest_changes() {
    git diff --cached --name-only
}

function CLIENT_COMMAND() {
   ng lint && npm test
}

function BACKEND_COMMAND() {
   ./mvnw clean test
}

WORKING_DIRECTORY="$(pwd)"
DIR_CLIENT_CHANGES=$(get_latest_changes client)
DIR_BACKEND_CHANGES=$(get_latest_changes backend)

function run_linter() {
   if [[ $1 =~ $2 ]]; then
      cd "$WORKING_DIRECTORY"
      cd $3
      $4
   fi
}

run_linter "$DIR_CLIENT_CHANGES" "client/" client CLIENT_COMMAND
run_linter "$DIR_BACKEND_CHANGES" "backend/" backend BACKEND_COMMAND