@startuml

package controller {
    abstract class AbstractController {
        -{static} final Logger LOG
    }

    class UserController extends AbstractController {
        -final UserService userService
        +UserController(UserService userService)
        ~List<User> all()
        ~User createUser(@RequestBody User user)
        ~User getUser(@PathVariable Long id)
    }

    class StockController extends AbstractController {
        -final StockService stockService
        +StockController(StockService stockService)
        ~List<Stock> all()
        ~Stock createUser(@RequestBody Stock stock)
        ~Stock getStock(@PathVariable Long id)
    }

    class TransactionController extends AbstractController {
        -final TransactionService transactionService
        +TransactionController(TransactionService transactionService)
        ~List<Transaction> all()
        ~Transaction createTransaction(@RequestBody Transaction transaction)
        ~Transaction getTransaction(@PathVariable Long id)
    }
}

@enduml