@startuml

package IEXCloud {
    class IEXCloudFacade {
        +final IEXCloudAPI
        +final IEXCloudService

        Stock getStockInfo(String stockLabel)
        Company getCompanyInfo(String companyName)
        Chart getChart(String ChartName)
        Book getBookInfo(String bookName)

    }

    class IEXCloudService {

    }

    class IEXCloudAPI {
    String apiKey
    }
}

IEXCloudFacade *-- IEXCloudService
IEXCloudFacade *-- IEXCloudAPI

@enduml