@startuml

/'
' MoneyTree's main package
'/
package com.capstone.moneytree {

    /'
    ' Gathers all packages together
    '/
    !include ./ControllerPackage.puml
    !include ./ServicePackage.puml
    !include ./DaoPackage.puml
    !include ./ModelPackage.puml
    !include ./AlpacaPackage.puml
    !include ./FacadePackage.puml

    class MoneyTreeApplication {
        +{static} void main(String[] args)
    }

    /'
    ' Package2Package Relationships
    '/
    DefaultUserService *-- UserDao

    DefaultStockService *-- StockDao

    DefaultTransactionService *-- TransactionDao

    UserController *-- UserService

    StockController *-- StockService

    TransactionController *-- TransactionService

    skinparam linetype ortho

}

@enduml