@startuml

/'
 ' MoneyTree's main package
 '/
package com.capstone.moneytree {

   /'
    ' Gathers all packages together
    '/
    !include ./ControllerPackage.puml
    !include ./DaoPackage.puml
    !include ./ModelPackage.puml
    !include ./ServicePackage.puml

    class MoneyTreeApplication {
        +{static} void main(String[] args)
    }

   /'
    ' Package2Package Relationships
    '/
    DefaultUserService *-- UserDao
    DefaultUserService *-- User

    UserController *-- UserService
    UserController *-- User

}

@enduml