@startuml

package Feed {
    class FeedFacade {
        +final FeedService

        List<Activity> getActivities(User user)
        Activity createActivity(Activity activity)
        Activity updateActivity(String activityId)
        follows(String userId)
        boolean deleteActivity(String activityId)

    }

    class IEXCloudService {

    }

    class IEXCloudAPI {
    String apiKey
    }
}

FeedFacade *-- FeedService
FeedFacade *-- FeedAPI

@enduml