name: CD Pipeline

on:
  push:
    branches:
      - issue/#70-setup-devops-pipeline

# TODO: (Build --> Publish --> Deploy-UAT --> Cleanup)
jobs:
  # job_1:
  #   name: Build & Publish
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Publish Frontend
  #       uses: elgohr/Publish-Docker-Github-Action@master
  #       with:
  #         name: dpigeon/money-tree/frontend
  #         registry: docker.pkg.github.com
  #         username: ${{ secrets.USERNAME }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #         workdir: client
  #         dockerfile: Dockerfile
  #         tags: latest

  #     - name: Publish Backend
  #       uses: elgohr/Publish-Docker-Github-Action@master
  #       with:
  #         name: dpigeon/money-tree/backend
  #         registry: docker.pkg.github.com
  #         username: ${{ secrets.USERNAME }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #         workdir: backend
  #         dockerfile: Dockerfile
  #         tags: latest

  job_1:
    name: Deploy-UAT
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.UAT_DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          port: ${{ secrets.DROPLET_PORT }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            sh deploy.sh $GITHUB_USERNAME $GITHUB_TOKEN
