name: CD Pipeline

# CD will be triggered only on push on master branch
on:
  push:
    branches:
      - issue/#70-setup-devops-pipeline

# TODO: It will run 4 jobs in series (Build --> Publish --> Deploy-UAT --> Cleanup)
jobs:
  # TODO: a job that will build docker image and push to heroku registry. We can pull & push if no updates
  job_1:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          docker_compose_file: "./docker-compose.yml"
          heroku_apps: '[{"imagename":"client","appname":${{ secrets.HEROKU_UAT_ENV_NAME }},"apptype":"web"},{"imagename":"backend","appname":${{ secrets.HEROKU_UAT_ENV_NAME }},"apptype":"web"}]'
