name: CD Pipeline

# CD will be triggered only on push on master branch
on: 
  push:
    branches:
      - master
      
# It will run 4 jobs in series (Build --> Publish --> Deploy-UAT --> Cleanup)
jobs:
  job_1:
    name: Build
    
  job_2:
    needs: job_1
    name: Publish
    
  job_3:
    needs: job_2
    name: Deploy-UAT
    
  job_4:
    needs: job_3
    name: Cleanup