name: CI Pipeline

# CI will be triggered only when making a PR to the dev branch
on:
  pull_request:
    branches:
      - '*'
      - dev
      
# It will run 4 jobs in series (Lint --> Tests --> Package --> SonarCloud)
jobs:
  job_1:
    name: Lint
    
  job_2:
    needs: job_1
    name: Tests
    
  job_3:
    needs: job_2
    name: Package
    
  job_4:
    needs: job_3
    name: SonarCloud