name: CI Pipeline

# # CI will be triggered only when making a PR to the dev branch
# on:
#   pull_request:
#     branches:
#       - "*"
#       - dev

# TEMPORARY for testing
on:
  push:
    branches:
      - "*"
      - issue/#70-setup-devops-pipeline

# We have 2 main jobs:
#   1. Integration: (Install) --> Lint --> Tests --> Package
#   2. Quality Check
jobs:
  job_1:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1.4.4
        with:
          node-version: "12.x"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Node Modules
        id: node-modules
        uses: actions/cache@v2.1.1
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          # Used to create a place to store node_modules to reuse it in other steps
          path: ~/.npm
          key: ${{ runner.OS }}-nodejs-frontend-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-nodejs-frontend-
            ${{ runner.OS }}-nodejs-

      - name: Install Frontend Dependencies
        working-directory: ./client
        if: steps.node-modules.outputs.cache-hit != 'true' # Checks if node has modules as cache already
        run: npm i

      # Note: to interact with ng on the VM (when building the app for example), @angular/cli & @angular-devkit/build-angular must be installed
      # It is the case here with the linter
      - name: Frontend Lint
        working-directory: ./client
        run: npm i -g @angular/cli &&
          npm i --save-dev @angular-devkit/build-angular &&
          npm run lint

      - name: Frontend Tests
        working-directory: ./client
        run: npm test

      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11.0.8

      - name: Cache Maven
        id: maven-dependencies
        uses: actions/cache@v2.1.1
        # maven cache files are stored in `~/.m2/repository` on Linux/macOS
        # Used to create place to store libraries to resure it in other steps
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Backend Dependencies
        working-directory: ./backend
        if: steps.maven-dependencies.outputs.cache-hit != 'true' # Checks if maven has dependencies as cache already
        run: bash ./mvnw install

      - name: Backend Tests
        working-directory: ./backend
        run: bash ./mvnw clean test
      
      - name: Backend Package
        working-directory: ./backend
        run: bash ./mvnw package
      
      - name: Backend Run
        working-directory: ./backend/target
        run: java -jar backend.jar

      # TODO: Package sub-job
      # This sub-job will be use docker to package our application by building it and creating an image of it
      # Used to know if the app can be built properly before shipping it in deployment
      # Use the cache (dependencies) of both client & backend defined above

  # TODO: SonarCloud

  # job_2:
  #   needs: job_2
  #   name: SonarCloud
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
