name: Deploy to Production

# TODO: This workflow will be triggered on a manual click
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy-Production
    runs-on: ubuntu-latest
    steps:
      - name: TODO
        run: echo "TODO"
