name: Deploy to UAT

# TODO: This workflow will be triggered on a manual click
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Environment"
        required: false
        default: "warning"
      tags:
        description: "Deploy to environment"

jobs:
  job_1:
    name: Deploy-UAT
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.UAT_DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          port: ${{ secrets.DROPLET_PORT }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            docker rm -f frontend &>/dev/null && echo 'Removed old frontend container.'
            docker rm -f backend &>/dev/null && echo 'Removed old frontend container.'
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/dpigeon/money-tree/frontend:latest
            docker pull docker.pkg.github.com/dpigeon/money-tree/backend:latest
            docker run -dit -p 4200:80 --name frontend docker.pkg.github.com/dpigeon/money-tree/frontend:latest
            docker run -dit -p 8080:8080 --name backend docker.pkg.github.com/dpigeon/money-tree/backend:latest
