name: Deploy to Production

# TODO: This workflow will be triggered on a manual click
on:
  workflow_dispatch:

jobs:
  job_1:
    name: Deploy-Prod
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.PROD_DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          port: ${{ secrets.DROPLET_PORT }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            docker stop $(docker ps -a -q)
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/dpigeon/money-tree/frontend:latest
            docker pull docker.pkg.github.com/dpigeon/money-tree/backend:latest
            docker run -dit -p 80:80 docker.pkg.github.com/dpigeon/money-tree/frontend:latest
            docker run -dit -p 8080:8080 docker.pkg.github.com/dpigeon/money-tree/backend:latest
